import {
    Caveat_Brush,
    Exo_2,
    Geist,
    Geist_Mono,
    Irish_Grover,
    Orbitron,
} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const jaapokki = localFont({
    src: "../../public/fonts/Jaapokki-Regular.otf",
    weight: "400",
    variable: "--font-jaapokki",
});
const jaapokkiEnchance = localFont({
    src: "../../public/fonts/Jaapokkienchance-Regular.otf",
    weight: "400",
    variable: "--font-jaapokki-enchance",
});
const jaapokkiSubtract = localFont({
    variable: "--font-jaapokki-subtract",
    src: "../../public/fonts/Jaapokkisubtract-Regular.otf",
    weight: "400",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const IrishGover = Irish_Grover({
    variable: "--font-irish-grover",
    subsets: ["latin"],
    weight: "400",
});
const CaveatBrush = Caveat_Brush({
    variable: "--font-caveat-brush",
    subsets: ["latin"],
    weight: "400",
});

const orbitron = Orbitron({
    variable: "--font-orbitron",
    subsets: ["latin"],
    // weight: "400 700",
});

import { ViewTransitions } from "next-view-transitions";

export default function RootLayout({ children }) {
    return (
        <ViewTransitions>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased ${IrishGover.variable} ${CaveatBrush.variable} ${orbitron.variable} ${jaapokki.variable} ${jaapokkiEnchance.variable} ${jaapokkiSubtract.variable}`}
                >
                    {children}
                </body>
            </html>
        </ViewTransitions>
    );
}
